name: Build and Push NVIDIA Stable Tuxedo Images

on:
  push:
    paths-ignore:
      - "README.md"
      - "docs/**"
      - "*.md"
  pull_request:
    paths-ignore:
      - "README.md"
      - "docs/**"
      - "*.md"
  schedule:
    - cron: "0 2 * * 0" # Every Sunday at 2 AM UTC
  workflow_dispatch:

permissions:
  contents: write
  packages: write
  id-token: write

env:
  REGISTRY: ghcr.io

jobs:
  check-base-images:
    runs-on: ubuntu-latest
    outputs:
      skip_all: ${{ steps.check.outputs.skip_all }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y skopeo jq

      - name: Check base image digests
        id: check
        run: |
          bash scripts/check-base-images.sh --images ghcr.io/ublue-os/aurora-nvidia:stable ghcr.io/ublue-os/aurora-dx-nvidia:stable ghcr.io/ublue-os/bluefin-nvidia:stable ghcr.io/ublue-os/bluefin-dx-nvidia:stable ghcr.io/ublue-os/bazzite-nvidia:stable ghcr.io/ublue-os/bazzite-nvidia-open:stable ghcr.io/ublue-os/bazzite-deck-nvidia:stable ghcr.io/ublue-os/bazzite-gnome-nvidia:stable ghcr.io/ublue-os/bazzite-gnome-nvidia-open:stable ghcr.io/ublue-os/bazzite-deck-nvidia-gnome:stable

  build-and-test:
    needs: check-base-images
    if: needs.check-base-images.outputs.skip_all == 'false'
    runs-on: ubuntu-latest
    strategy:
      matrix:
        variant: [aurora-nvidia-stable, aurora-dx-nvidia-stable, bluefin-nvidia-stable, bluefin-dx-nvidia-stable, bazzite-nvidia-stable, bazzite-nvidia-open-stable, bazzite-deck-nvidia-stable, bazzite-gnome-nvidia-stable, bazzite-gnome-nvidia-open-stable, bazzite-deck-nvidia-gnome-stable]
        include:
          # Aurora NVIDIA variants
          - variant: aurora-nvidia-stable
            containerfile: containerfiles/Containerfile.aurora-nvidia
            base_image: ghcr.io/ublue-os/aurora-nvidia:stable
            tag: stable
            image_name: okazakee/aurora-nvidia-tuxedo
            description: "Aurora NVIDIA Stable with Tuxedo drivers and TCC"
          - variant: aurora-dx-nvidia-stable
            containerfile: containerfiles/Containerfile.aurora-dx-nvidia
            base_image: ghcr.io/ublue-os/aurora-dx-nvidia:stable
            tag: stable
            image_name: okazakee/aurora-dx-nvidia-tuxedo
            description: "Aurora DX NVIDIA Stable with Tuxedo drivers and TCC "
          # Bluefin NVIDIA variants
          - variant: bluefin-nvidia-stable
            containerfile: containerfiles/Containerfile.bluefin-nvidia
            base_image: ghcr.io/ublue-os/bluefin-nvidia:stable
            tag: stable
            image_name: okazakee/bluefin-nvidia-tuxedo
            description: "Bluefin NVIDIA Stable with Tuxedo drivers and TCC"
          - variant: bluefin-dx-nvidia-stable
            containerfile: containerfiles/Containerfile.bluefin-dx-nvidia
            base_image: ghcr.io/ublue-os/bluefin-dx-nvidia:stable
            tag: stable
            image_name: okazakee/bluefin-nvidia-tuxedo-dx
            description: "Bluefin DX NVIDIA Stable with Tuxedo drivers and TCC"
          # Bazzite NVIDIA variants
          - variant: bazzite-nvidia-stable
            containerfile: containerfiles/Containerfile.bazzite-nvidia
            base_image: ghcr.io/ublue-os/bazzite-nvidia:stable
            tag: stable
            image_name: okazakee/bazzite-nvidia-tuxedo
            description: "Bazzite NVIDIA Stable with Tuxedo drivers and TCC"
          - variant: bazzite-nvidia-open-stable
            containerfile: containerfiles/Containerfile.bazzite-nvidia-open
            base_image: ghcr.io/ublue-os/bazzite-nvidia-open:stable
            tag: stable
            image_name: okazakee/bazzite-nvidia-open-tuxedo
            description: "Bazzite NVIDIA Open Stable with Tuxedo drivers and TCC"
          - variant: bazzite-deck-nvidia-stable
            containerfile: containerfiles/Containerfile.bazzite-deck-nvidia
            base_image: ghcr.io/ublue-os/bazzite-deck-nvidia:stable
            tag: stable
            image_name: okazakee/bazzite-deck-nvidia-tuxedo
            description: "Bazzite Deck NVIDIA Stable with Tuxedo drivers and TCC"
          - variant: bazzite-gnome-nvidia-stable
            containerfile: containerfiles/Containerfile.bazzite-gnome-nvidia
            base_image: ghcr.io/ublue-os/bazzite-gnome-nvidia:stable
            tag: stable
            image_name: okazakee/bazzite-gnome-nvidia-tuxedo
            description: "Bazzite GNOME NVIDIA Stable with Tuxedo drivers and TCC"
          - variant: bazzite-gnome-nvidia-open-stable
            containerfile: containerfiles/Containerfile.bazzite-gnome-nvidia-open
            base_image: ghcr.io/ublue-os/bazzite-gnome-nvidia-open:stable
            tag: stable
            image_name: okazakee/bazzite-gnome-nvidia-open-tuxedo
            description: "Bazzite GNOME NVIDIA Open Stable with Tuxedo drivers and TCC"
          - variant: bazzite-deck-nvidia-gnome-stable
            containerfile: containerfiles/Containerfile.bazzite-deck-nvidia-gnome
            base_image: ghcr.io/ublue-os/bazzite-deck-nvidia-gnome:stable
            tag: stable
            image_name: okazakee/bazzite-deck-nvidia-gnome-tuxedo
            description: "Bazzite Deck NVIDIA GNOME Stable with Tuxedo drivers and TCC"

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to Container Registry
        uses: docker/login-action@v3
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GHCR_PAT }}

      - name: Extract MOK Certificates from Secrets
        run: |
          mkdir -p overlay/usr/share/aurora-tuxedo/mok/
          echo "${{ secrets.MOK_PRIVATE_KEY }}" > overlay/usr/share/aurora-tuxedo/mok/MOK.key
          echo "${{ secrets.MOK_CERTIFICATE_PEM }}" > overlay/usr/share/aurora-tuxedo/mok/MOK.crt
          echo "${{ secrets.MOK_CERTIFICATE_DER }}" | base64 -d > overlay/usr/share/aurora-tuxedo/mok/MOK.der

      - name: Extract metadata
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: ${{ env.REGISTRY }}/${{ matrix.image_name }}
          tags: |
            type=ref,event=branch
            type=ref,event=pr
            type=sha,prefix={{branch}}-
            type=raw,value=${{ matrix.tag }},enable={{is_default_branch}}
            type=semver,pattern={{version}}
            type=semver,pattern={{major}}.{{minor}}
            type=semver,pattern={{major}}

      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ${{ matrix.containerfile }}
          platforms: linux/amd64
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          cache-from: type=gha
          cache-to: type=gha,mode=max
          provenance: false

      - name: Install Cosign
        uses: sigstore/cosign-installer@v3

      - name: Sign with Cosign
        env:
          TUF_ROOT: ${{ secrets.TUF_ROOT }}
        run: |
          echo "${{ secrets.COSIGN_PRIVATE_KEY }}" | cosign sign --yes ${{ env.REGISTRY }}/${{ matrix.image_name }}:${{ matrix.tag }}
