name: Build and Push Aurora Stable Tuxedo Images

on:
  push:
    branches: [main, master]
    paths-ignore:
      - "README.md"
      - "docs/**"
      - "*.md"
  pull_request:
    branches: [main, master]
    paths-ignore:
      - "README.md"
      - "docs/**"
      - "*.md"
  schedule:
    - cron: "0 2 * * 0" # Every Sunday at 2 AM UTC
  workflow_dispatch:

permissions:
  contents: write
  packages: write
  id-token: write

env:
  REGISTRY: ghcr.io

jobs:
  check-base-images:
    runs-on: ubuntu-latest
    outputs:
      skip_all: ${{ steps.check.outputs.skip_all }}
      build_aurora_stable: ${{ steps.check.outputs.build_aurora_stable }}
      build_aurora_dx_stable: ${{ steps.check.outputs.build_aurora_dx_stable }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y skopeo jq

      - name: Check base image digests
        id: check
        env:
          TUF_ROOT: ${{ secrets.TUF_ROOT }}
        run: |
          bash scripts/check-base-images.sh --images ghcr.io/ublue-os/aurora:stable ghcr.io/ublue-os/aurora-dx:stable

      - name: Debug outputs
        if: always()
        run: |
          echo "skip_all: ${{ steps.check.outputs.skip_all }}"
          echo "build_aurora_stable: ${{ steps.check.outputs.build_aurora_stable }}"
          echo "build_aurora_dx_stable: ${{ steps.check.outputs.build_aurora_dx_stable }}"

  build-and-test:
    needs: check-base-images
    if: needs.check-base-images.outputs.skip_all == 'false'
    runs-on: ubuntu-latest
    strategy:
      matrix:
        variant: [aurora-stable, aurora-dx-stable]
        include:
          - variant: aurora-stable
            containerfile: containerfiles/Containerfile.aurora
            base_image: ghcr.io/ublue-os/aurora:stable
            tag: stable
            image_name: okazakee/aurora-tuxedo
            description: "Aurora Stable with Tuxedo drivers and TCC"
          - variant: aurora-dx-stable
            containerfile: containerfiles/Containerfile.aurora-dx-stable
            base_image: ghcr.io/ublue-os/aurora-dx:stable
            tag: stable
            image_name: okazakee/aurora-tuxedo-dx
            description: "Aurora DX Stable with Tuxedo drivers and TCC"

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to Container Registry
        uses: docker/login-action@v3
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GHCR_PAT }}

      - name: Extract metadata
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: ${{ env.REGISTRY }}/${{ matrix.image_name }}
          tags: |
            type=ref,event=branch
            type=ref,event=pr
            type=sha,prefix={{branch}}-
            type=raw,value=${{ matrix.tag }},enable={{is_default_branch}}
            type=semver,pattern={{version}}
            type=semver,pattern={{major}}.{{minor}}
            type=semver,pattern={{major}}

      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ${{ matrix.containerfile }}
          platforms: linux/amd64
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          cache-from: type=gha
          cache-to: type=gha,mode=max
          provenance: false

      - name: Install Cosign
        uses: sigstore/cosign-installer@v3

      - name: Sign with Cosign
        env:
          TUF_ROOT: ${{ secrets.TUF_ROOT }}
        run: |
          echo "${{ secrets.COSIGN_PRIVATE_KEY }}" | cosign sign --yes ${{ env.REGISTRY }}/${{ matrix.image_name }}:${{ matrix.tag }}
